### ISSUE TITLE
Xahau PaymentChannel network fee not found

### ISSUE THREAD

**Issue by desimmons** [XRPL-Labs/Xaman-App#111]
**Describe the bug**
When submitting a PaymentChannelCreate TX using MAINNET or TESTNET, the "PublicKey"  field does not need specifying. For example:
```
{
        "TransactionType": "PaymentChannelCreate",
        "Amount": amount,
        "Destination": destinationAddress,
        "SettleDelay": 1209600
}
```
IIUC, [this](https://github.com/XRPL-Labs/Xaman-App/blob/e6b13d877f4b7178ac51b51d345edc9fee81ee8c/src/common/libs/ledger/transactions/genuine/BaseTransaction.ts#L122) line does the job of injecting the PublicKey later. 

However, if I do the same with XAHAU or XAHAUTESTNET, it is unable to load the network fee. The following [VIDEO DEMO OF BUG](https://youtu.be/91oyfzS8qoo) highlights the behaviour.

**Expected behavior**
I would expect PaymentChannelCreate to behave similarly across network types

**Screenshots**
[VIDEO DEMO OF BUG](https://youtu.be/91oyfzS8qoo)

### Environment

What build of XUMM are you running? Please provide the full version (you can find it in Settings > Advanced).

* XUMM version: 2.8.2.315736

What device are you running XUMM on?

* Manufacturer: Huawei
* Model: HONOR X7a
* OS version: 12
* Platforms
  * [ ] iOS
  * [x] Android

### Additional context

Attach crash logs if available. Please ensure that these files do not contain any personal information.

**Comment by WietseWind** [comment]
The problem seems to be the NetworkID is missing from the transaction payload. Which makes the network unable to determine the fee because it's invalid.

Did you add the NetworkID field to the payload?

**Comment by WietseWind** [comment]
Force network isn't the same. That's a layer two, software field.

NetworkID is the native mandatory field fo4 transactions. Please try adding it.
