### ISSUE TITLE
XRP amount exchanged badly displayed

### ISSUE THREAD

**Issue by adrienbailliard** [XRPL-Labs/Xaman-App#117]
There is two extra minus when the wallet lost money during a transaction due to network fees when displaying xrp amount.

### Step to reproduce the behavior
 • Exchange 1 drop for any token at the market price.

### Expected behavior
`0.000001` instead of `--0.000001`.

### Wrong behavior
![IMG_1839](https://github.com/user-attachments/assets/52b786c2-b7b8-4c7c-b978-c3d02914dc84)

### Pretty much correct behavior
It should display `0.0001 XRP`.
![IMG_1840](https://github.com/user-attachments/assets/7c74a47e-945f-4ccd-9aa7-8653f6da43fd)

### Environment
* XUMM version: 3.0.1.1
* Manufacturer: Apple
* Model: iPhone 14
* OS version: 18.0.1
* Platforms
  * IOS

### Context
It seems that network fees are badly managed.

**Comment by Emmaward090** [comment]
> There is two extra minus when the wallet lost money during a transaction due to network fees when displaying xrp amount.
> 
> ### Step to reproduce the behavior
> • Exchange 1 drop for any token at the market price.
> 
> ### Expected behavior
> `0.000001` instead of `--0.000001`.
> 
> ### Wrong behavior
> ![IMG_1839](https://private-user-images.githubusercontent.com/187867341/384683979-52b786c2-b7b8-4c7c-b978-c3d02914dc84.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjUyOTksIm5iZiI6MTczMTI2NDk5OSwicGF0aCI6Ii8xODc4NjczNDEvMzg0NjgzOTc5LTUyYjc4NmMyLWI3YjgtNGM3Yy1iOTc4LWMzZDAyOTE0ZGM4NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxODU2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MGU2OTZmYzI0YWMzZDdiOGQ0ZDIxMTEwNjc2ZGQ3YzUzYzkwZDRlZmExYTZhOGQ2NWFiZGJjOTcxNzI3ODFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-pOBe4Nv9JW1zh8ghAafEsDdUH97CO3BRKH_WDCb_pk)
> 
> ### Pretty much correct behavior
> It should display `0.0001 XRP`. ![IMG_1840](https://private-user-images.githubusercontent.com/187867341/384685628-7c74a47e-945f-4ccd-9aa7-8653f6da43fd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzEyNjUyOTksIm5iZiI6MTczMTI2NDk5OSwicGF0aCI6Ii8xODc4NjczNDEvMzg0Njg1NjI4LTdjNzRhNDdlLTk0NWYtNGNjZC05YWE3LTg2NTNmNmRhNDNmZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExMFQxODU2MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTc2YjhjYmEyMjJiMTkzZjA4YmYwZTY0ZGYwZmNjMjlmMmVlNDgxMzNjODFlMjcxNjlkNGYxZWNhNjdlMDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.3Mi-kCWHhjCZoeBreKS3ZlkvJrSB32H0hZTujd98Db4)
> 
> ### Environment
> * XUMM version: 3.0.1.1
> * Manufacturer: Apple
> * Model: iPhone 14
> * OS version: 18.0.1
> * Platforms
>   
>   * IOS
> 
> ### Context
> It seems that network fees are badly managed.



It sounds like there might be a bug in the display of the XRP amount. Normally, network fees shouldn't show as extra negative amounts. Here are a few steps you can take:

Check Transaction Details: Look at the details of the transaction to see if the fees are being deducted correctly.
Update the App: Make sure your Tonkeeper app is up to date, as updates can fix bugs like this. Let me know if you need any more help!
@adrienbailliard

**Comment by WietseWind** [comment]
@N3TC4T -- = + :P

**Comment by N3TC4T** [comment]
Thanks, fixed, will be included in next release.

<img src="https://github.com/user-attachments/assets/c01b64ff-faa9-4c14-9aeb-290ba93b68e3"  width="200px"/>
