### ISSUE TITLE
Token Logo Submission Request for MSTAR

### ISSUE THREAD

**Issue by rodstar007** [XRPL-Labs/Xaman-App#130]
## Token Details
- **Issuer Address**: 	rwic6SgnZFpN7ZsNN3nm61pnzVu6pa4b8F
- **Token Code**: MSTAR
- **Decimals**: 0.01

## Logo Information
- **Logo URL**: https://imgur.com/a/201OhQs
- **Logo Format**: PNG, 256x256, transparent background (recommended).

## Additional Information (Optional)
- **Project Description**: Utility token for finance lending agency using the XRPL
- **Website**: maicoostar-financial.com
- **Social Media**: None yet

**Comment by WietseWind** [comment]
Please see: https://help.xaman.app/app/learning-more-about-xaman/adding-an-icon-logo-to-a-trust-line-in-xumm
